const dbDestinos = [
  {
    id: 1,
    title: "Carnaval en Purmamarca y Tilcara.",
    category: "Jujuy",
    stock: 100,
    imgurl: "",
    imgurl2: "",
    imgurl3: "",
    detail:
      "Para disfrutar a pleno en la Quebrada de Humahuaca, visitarás los pueblos más carnavaleros: Purmamarca y Tilcara, en donde nuestro guía los invitará a la fiesta, comparsas y bailes con la gente local y turistas que llegan de todo el mundo para un evento único.",
    price: 0,
  },
  {
    id: 2,
    title: "Cachi, Valles Calchaquíes",
    category: "Salta",
    stock: 100,
    imgurl: "",
    imgurl2: "",
    imgurl3: "",
    detail:
      "Recorrer paisajes majestuosos, viajar al pasado y disfrutar de la tranquilidad que un pueblo vallisto, como Cachi, nos puede brindar. Viajarás por rutas escénicas (Quebrada de Escoipe y Cuesta del Obispo) que junto con el encantador destino, forman un combo cautivante.",
    price: 0,
  },
  {
    id: 3,
    title: "Cafayate, Valles Calchaquíes        ",
    category: "Salta",
    stock: 7,
    imgurl: "",
    imgurl2: "",
    imgurl3: "",
    detail:
      "Un paseo por una quebrada rojiza, donde cada formación geológica tallada por el viento y el agua nos regala hermosas postales de la precordillera, una antesala más que merecida para Cafayate, corazón del Valle Calchaquí donde siempre brilla el sol y te espera el mejor vino de altura.",
    price: 0,
  },
  {
    id: 4,
    title: "City tour: Salta y San Lorenzo    ",
    category: "Salta",
    stock: 7,
    imgurl: "",
    imgurl2: "",
    imgurl3: "",
    detail:
      "Échale un vistazo a la ciudad de Salta y sus alrededores en tan solo medio dia!",
    price: 0,
  },
  {
    id: 5,
    title: "Salinas Grandes y Purmamarca    ",
    category: "Salta",
    stock: 7,
    imgurl: "",
    imgurl2: "",
    imgurl3: "",
    detail:
      "Un paseo de altura que nos lleva a conocer el salar más visitado del Norte Argentino, atravesando los pueblos más pintorescos de la zona. Deleita tu espíritu aventurero con los paisajes más llamativos de la Puna Argentina",
    price: 0,
  },
  {
    id: 6,
    title: "Cataratas Argentinas",
    category: "Iguazu",
    stock: 7,
    imgurl: "",
    imgurl2: "",
    imgurl3: "",
    detail: "Del lado argentino se podrá caminar, literalmente, sobre las mismísimas cataratas. El recorrido es de aproximadamente 10 km, en cuyos tramos el uso del Tren Ecológico acorta las distancias, y las pasarelas acondicionadas permiten llegar a los mejores saltos de agua, dividiendo al recorrido en circuito Garganta del Diablo, Superior e Inferior.",
    price: 0,
  },
  {
    id: 7,
    title: "Cataratas Brasileras",
    category: "Iguazu",
    stock: 7,
    imgurl: "",
    imgurl2: "",
    imgurl3: "",
    detail: "Una nueva y maravillosa vista de las imponentes Cataratas del Iguazù, esta vez del lado del vecino país Brasil donde se puede apreciar toda su belleza natural y podràs conseguir esa foto panorámica tan especial que estabas buscando.",
    price: 0,
  },
  {
    id: 8,
    title: "Cataratas Brasileras y Parque Das Aves",
    category: "Iguazu",
    stock: 7,
    imgurl: "",
    imgurl2: "",
    imgurl3: "",
    detail: "Situado a metros de las maravillosas Cataratas do Iguaçu en la ciudad de Foz do Iguaçu, Brasil el Parque das Aves es la única institución del mundo enfocada en la conservación de las aves de la Mata Atlàntica, ofreciendo una experiencia mágica de contacto cercano y encantador con ellas.",
    price: 0,
  },
  {
    id: 9,
    title: "Humahuaca desde Jujuy, Purmamarca o Tilcara",
    category: "Jujuy",
    stock: 7,
    imgurl: "",
    imgurl2: "",
    imgurl3: "",
    detail: "Un paseo por una quebrada imponente, donde predominan los colores en los cerros, gracias a miles de años de oxidación de los minerales en ellos. Los pueblos, paisajes, la cultura y su gente son los principales protagonistas de esta excursión.",
    price: 0,
  },
  {
    id: 10,
    title: "Iruya desde Jujuy, Purmamarca o Tilcara",
    category: "Jujuy",
    stock: 7,
    imgurl: "",
    imgurl2: "",
    imgurl3: "",
    detail: "Déjate sorprender por los valles de altura del norte de Argentina con esta excursión que te permitirá conocer pintorescos pueblos como Purmamarca, Humahuaca e Iruya. con su gran historia y cultura ¡Te sorprenderán!",
    price: 0,
  },
  {
    id: 11,
    title: "City tour en Ciudad de Jujuy desde hoteles céntricos de la ciudad",
    category: "Jujuy",
    stock: 7,
    imgurl: "",
    imgurl2: "",
    imgurl3: "",
    detail: "Échale un vistazo a la ciudad de Jujuy y sus alrededores en tan solo medio dia!",
    price: 0,
  },
  {
    id: 12,
    title: "City tour Tucumán",
    category: "Tucuman",
    stock: 7,
    imgurl: "",
    imgurl2: "",
    imgurl3: "",
    detail: "Un breve paseo por la ciudad de San Miguel de Tucumán nos lleva por un recorrido a través de la historia y lugares más interesantes del casco central.",
    price: 0,
  },
  {
    id: 13,
    title: "Tucuman + Tafí del valle + Ruinas de Quilmes",
    category: "Tucuman",
    stock: 7,
    imgurl: "",
    imgurl2: "",
    imgurl3: "",
    detail: "Una visita a la ciudad de la magnífica entrada, así catalogada por los indígenas diaguita.",
    price: 0,
  },
  {
    id: 14,
    title: "Paisajes y Yungas",
    category: "Tucuman",
    stock: 7,
    imgurl: "",
    imgurl2: "",
    imgurl3: "",
    detail: "Realizamos un recorrido que nos llevará dentro en las Yungas Tucumanas.",
    price: 0,
  },
  {
    id: 15,
    title: "Quebrada de Humahuaca",
    category: "Salta",
    stock: 7,
    imgurl: "",
    imgurl2: "",
    imgurl3: "",
    detail: "Un paseo por una quebrada imponente, donde predominan los colores en los cerros, gracias a miles de años de oxidación de los minerales en ellos. Los pueblos, paisajes, la cultura y su gente son los principales protagonistas de esta excursión.",
    price: 0,
  },
];
